### ISSUE TITLE
Keybind bug

### ISSUE THREAD

**Issue by dendend** [PowerOfUniverse/Surviv.io-Cheats#11]
When the "Equip other guns" set to right mouse key on keybind, I can not punch.(I held my guns.)
I want to equip other guns by right click , even while holding Left shit key.
Please fix it.
I apologize for my poor English.

**Comment by PowerOfUniverse** [comment]
The right button is responsible for the quick change of weapons.
I will try to remedy this.

**Comment by dendend** [comment]
I’m looking forward to it :)
Thank you for constantly updating !

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Surviv.io-Cheats/commit/edb25801cca6f60bab5d1c15115223f1c672253b
