### ISSUE TITLE
Suggestion: make triggerbot conditional on lmb

### ISSUE THREAD

**Issue by cornmask** [PowerOfUniverse/Surviv.io-Cheats#18]
Hi,
Nice work on the triggerbot! A simple yet clever addition to the whole mechanics.
But in its current state it makes LMB usage slightly redundant for me.
But here is what i propose: since you can always shoot in desired direction and time using holding SHIFT - for tripping barrels and other purposes, why not make trigerrbot active only when LMB is pressed?

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Surviv.io-Cheats/projects/1
I will add it in my spare time, only on the right mouse button.
