### ISSUE TITLE
Zoom level changeable in-game

### ISSUE THREAD

**Issue by holidaynights** [PowerOfUniverse/Surviv.io-Cheats#19]
Very unique take on features for the extension!

Could you make the zoom level changeable (ie. zoom in/out) via scroll wheel? Thanks!

**Comment by holidaynights** [comment]
Oh here's an actual bug I've encountered: 
The team emote menu (e.g. ammo pings, location pings, etc.) doesn't work/show up when your extension is enabled. The non-team emote menu (e.g. smilies) works fine with the keybindings.

**Comment by PowerOfUniverse** [comment]
When you press both buttons it still works...
