### ISSUE TITLE
Files gone

### ISSUE THREAD

**Issue by zbot473** [PowerOfUniverse/Surviv.io-Cheats#2]
Are the rest of the files gone? I don't see them. I had your repo cloned locally though so I can give you that if needed

**Comment by PowerOfUniverse** [comment]
I just used a different method of loading these files. Everything is as it was + corrections to recent problems.

**Comment by PowerOfUniverse** [comment]
I did it because a lot of people are stealing these files. They change the name of the author to his own and place it as his own. Of course, this will not solve the problem, but it will make it a bit difficult.
