### ISSUE TITLE
Possible to Make Auto-aim triggerable with Right Click

### ISSUE THREAD

**Issue by survivigod** [PowerOfUniverse/Surviv.io-Cheats#20]
Hey, is there any way to make auto aim trigger-able with right click? 
It just looks a lot less obvious while playing, and I like it that way.

**Comment by PowerOfUniverse** [comment]
At the moment not, but I will add it in the future;)

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Surviv.io-Cheats/projects/1
