### ISSUE TITLE
Locking on players

### ISSUE THREAD

**Issue by Xeroxytgt** [PowerOfUniverse/Surviv.io-Cheats#22]
Could u make it so it dosen't move your mouse so rapidly cuz it's obvious ur hacking >:(

**Comment by PanKot** [comment]
Then dont use it  ¯\_(ツ)_/¯

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/45599518-2beadc80-b9ed-11e8-8ae5-5729806ffd57.png)
