### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by IAmAHumanIThink** [PowerOfUniverse/Surviv.io-Cheats#23]
Whenever I enter a game, it just freezes the game. The numbers still move, though.

**Comment by PowerOfUniverse** [comment]
Can you send a photo of the version and errors from the console?

**Comment by IAmAHumanIThink** [comment]
<img width="413" alt="screen shot 2018-09-16 at 5 52 00 pm" src="https://user-images.githubusercontent.com/43094874/45601347-77938b00-b9d9-11e8-896c-d0a52eb7f209.png">

**Comment by IAmAHumanIThink** [comment]
<img width="680" alt="screen shot 2018-09-16 at 5 54 40 pm" src="https://user-images.githubusercontent.com/43094874/45601354-8ed27880-b9d9-11e8-8fe5-bbcdaf77e2d5.png">

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/45601359-ebe72200-ba0b-11e8-803a-64a3c328cf0c.png)

**Comment by PowerOfUniverse** [comment]
Just remove the old ones and download new ones ... Stop creating problems that are not there ... You're probably 9 ...?

**Comment by IAmAHumanIThink** [comment]
lmao

**Comment by PowerOfUniverse** [comment]
The box will burst for me soon.
Thanks :)

**Comment by IAmAHumanIThink** [comment]
i thought pressing update on the extension screen would update it 🤔

**Comment by PowerOfUniverse** [comment]
It only works on extensions from the main google store :)

**Comment by PowerOfUniverse** [comment]
However, you store files in a folder (on the desktop)
