### ISSUE TITLE
Spelling error xD

### ISSUE THREAD

**Issue by IAmAHumanIThink** [PowerOfUniverse/Surviv.io-Cheats#24]
"The plane is coming" is spelled like "The plane is comming"

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/45601427-e6d6a280-ba0c-11e8-82c8-caf9f1c8ea9b.png)
Hmmm?

**Comment by PowerOfUniverse** [comment]
Whatever... :)

**Comment by IAmAHumanIThink** [comment]
lol

**Comment by PowerOfUniverse** [comment]
I'm kidding ... I'll change it in the next update ... Thanks 😆
