### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by humphreygaming** [PowerOfUniverse/Surviv.io-Cheats#3]
on 9/7/2018 since the release of the update

**Comment by 00petar00** [comment]
game update was just released, give him some time to update the extension.
I bet it will be out in next 10 hours as he is usually quite fast with the updates.

**Comment by PowerOfUniverse** [comment]
I will be back in 4 hours and I will upgrade the extension.

**Comment by killercloudj** [comment]
You got this my guy

**Comment by PowerOfUniverse** [comment]
Ok, when I finish the tests, I will update it.

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Surviv.io-Cheats/commit/f8d805357c80fffb533e4cb4135b5292b648e0fb
