### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by colkat406** [PowerOfUniverse/Surviv.io-Cheats#4]
They did an update :(

Please try to fix as soon as possibbl thanks

**Comment by killercloudj** [comment]
Yay a new up date With new things and i am sorry on what happened I was wondering what had happened

**Comment by PowerOfUniverse** [comment]
Forgive us a lot of work today ... I'm gonna take it for a moment ...

**Comment by humphreygaming** [comment]
Take your time. At least Kalaborative's cheat works

**Comment by PowerOfUniverse** [comment]
Ok, when I finish the tests, I will update it.

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Surviv.io-Cheats/commit/f8d805357c80fffb533e4cb4135b5292b648e0fb
