### ISSUE TITLE
Notification of the hack is annoying

### ISSUE THREAD

**Issue by ALEXXANDRO23** [PowerOfUniverse/Surviv.io-Cheats#6]
How do I turn off the notification? that shows up when I activate the hack ..... It's kind of annoying :(

**Comment by PowerOfUniverse** [comment]
Ok, I will remove it ;)

**Comment by heatfist** [comment]
Hi, for some reason I can't use the cheat anymore, when it goes in game I see no characters or objectives. My Chrome has been updated automatically to the newest version.

**Comment by PowerOfUniverse** [comment]
Can you send photos of errors?

**Comment by PowerOfUniverse** [comment]
I also have the latest version and I have no problems.
![image](https://user-images.githubusercontent.com/42821489/45258565-0ab93900-b3ba-11e8-84ed-5b4cc89d43fb.png)

**Comment by PanKot** [comment]
No problems u say?
![image](https://user-images.githubusercontent.com/43040661/45258590-74394780-b3ba-11e8-9523-b7805bb15e76.png)

**Comment by PowerOfUniverse** [comment]
These are not problems ... The extension simply blocks external sources to be able to replace them ...

**Comment by heatfist** [comment]
It's okay now after a few F5 :)

**Comment by ALEXXANDRO23** [comment]
the notification that appears is * OK Cheat has been activated / deactivated * Thank you very much for responding and good trick! : D mate

**Comment by PowerOfUniverse** [comment]
Ok, I will update it when I finish the triggerBot.

**Comment by ALEXXANDRO23** [comment]
Thank you very much

**Comment by PowerOfUniverse** [comment]
https://streamable.com/5sy0z
TriggerBot - I did not use the right mouse button.

Soon :)

**Comment by alexvornoffice** [comment]
It is possible to add a dodge option so it will avoid the bullets automatically?

**Comment by PowerOfUniverse** [comment]
I will try to write it, but after writing the triggerBot.

**Comment by alexvornoffice** [comment]
I found this, I think may help - https://github.com/w3x731/survivIoAim/commit/225d4b669b5a32cb9f6781a10ffb003ecbd3d3ee

**Comment by PowerOfUniverse** [comment]
A nice piece of code ...
Thanks :)

**Comment by ALEXXANDRO23** [comment]
Friend I get an error at the start of the game is as follows * ERROR THIS EXTENTION CAN NOT WORK WITH THIS VERSION OF THE GAME! * If you had some solution you would help me a lot.............
I think it's because of the update of my Chrome ... I do not know :c Thanks

**Comment by PowerOfUniverse** [comment]
I will be back in 2 hours and I will upgrade the extension.

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Surviv.io-Cheats/commit/8fb69dea4940d6e34f6c629a5659cb47ff73de53
