### ISSUE TITLE
Hacks not working

### ISSUE THREAD

**Issue by Wakanda9Inch** [PowerOfUniverse/Surviv.io-Cheats#7]
Are you going to update the hack as it does not work after the rivers update

**Comment by Wakanda9Inch** [comment]
version 0.6.0

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/45258833-eceed280-b3bf-11e8-932f-56e9ef13e9b7.png)

**Comment by PowerOfUniverse** [comment]
As you can see works...

**Comment by PanKot** [comment]
Hack has been updated
![image](https://user-images.githubusercontent.com/43040661/45258869-874f1600-b3c0-11e8-9c87-6f78b30ccbe9.png)

**Comment by Wakanda9Inch** [comment]
thanks was getting scared
