### ISSUE TITLE
New game update and suggestions

### ISSUE THREAD

**Issue by 00petar00** [PowerOfUniverse/Surviv.io-Cheats#8]
Seems like they had some mini-update that wasn't in the notes and it still says that it is version 0.6.0. 
While cheat isn't working.

Suggestion 1:
I quite like the notifications for plane drops,if you rush to the line plane is going to, you have a good chance of getting the crate, i get much more  crates now but when cheat is turned on and off it gets quite "spammy" as i would call it i think that cheat should stay on between games when i am back on the  front page after i finish the round so there is no need for notification that it is turned on and off between games, maybe only when you load up the page so that you know that  cheat is working.

Suggestion 2:
Maybe make aim focus on things that will explode in the game, for example i like to get them a  hit away from blowing up and getting players to go near them when i am using a sniper, if a player is near anything that might explode and one bullet will make the object explode, it should focus the object instead of player.

Suggestion 3:
Tracker for the closest house or area when you spawn, could work like notifications just show up the direction of it, first few seconds can be critical when you spawn, this isn't really something important but it could be a valuable addition. 

Small problem 1:
I also found that if you use the option to not follow players between layers, for example if someone is underground and is going to come up not until he climbs the stairs aim won't focus  him, so aim won't work if they stay on stairs when you have that option toggled on. It works similar when i am on the stairs as aim won't focus on people until you step away from stairs while you both are in the range where you can shoot eachother.

I still don't remember everything i wanted to say, i should've written it down.. well anyways thanks for all the work and quick updates you do when the game is updated, i really appreciate it.

**Comment by alexvornoffice** [comment]
1. +1 for the stairs, not working aim
2. Maybe it is possible to make explosive barrels - red colored, so I can not hit them when I am near.
3. A line to the newest crate will be cool!
4. Aim is not perfect, when you are moving the aim is not taking this into consideration (I think) so hiting someone is hard when you are moving (I am not talking about recoil).
5. Stop automatically switching guns, that su**s.
6. Make elements that you need: level 3 armor, level 3 helmet colored (violet or purple) - so I will pick them without looking down to check what I need and looking on the map where to find, the same to ammo, to highlight items you only need.
7. When only one player left display a notification, maybe display for last 3 players: 3 players left, 2 players left, 1 player left so you can play more confident and more careful, because sometimes they kill each other and you think that more then one are alive...

**Comment by 00petar00** [comment]
alexvornoffice:

2. Could work with my suggestion about switching between players and barrels or any other objects that can explode if you hover the mouse over it  directly.

3.What i meant here is the line crate is going to fly over, its not really that useful to have a line to the nearest crate as it means that the create was already dropped and it is usually far away, you need to start running towards the line the plane will fly over and you have a much higher chance of getting there because of the new notifications, you are notified when plane is shown on the map and you pop the map open and see in which direction it is going to go, so you just try to reach the middle of the area he will fly over or if the middle is mansion, obviously its not there as most people just go to safe areas, so you can assume and walk towards the area you think it will drop for sure.

4. aim can't be perfect as how can it predict when and in which direction you will move? you need to be able to move in the direction you want, so compromise and stay in a spot for 1-2 seconds if you have precise weapon and zoom or try when you move to continue moving in the same direction a bit longer when you are trying to evade bullets. Its all about figuring out how you can deal out the most damage while taking less yourself, you don't necessarily need to dodge and try to dodge everything, sometimes when i am sure my weapon/armor is in much better shape a good example is having scar, you can usually stay in a spot and 95% people will die if you just shoot them as soon as you see them, you just stop moving so that aim can work perfectly,there's no way for you to lose that battle unless your armor is much worse, they  can't get close.

7. Usually when there's 2 people beside you left, its a good strategy to just wait for them to fight and as soon as one dies, you rush to find the last one before he can heal but that's only if you are chasing wins, its usually boring to wait, i guess it could be useful if you were warned when there is only 2 players besides you in solo.

**Comment by PowerOfUniverse** [comment]
1. https://github.com/PowerOfUniverse/Surviv.io-Cheats/commit/8fb69dea4940d6e34f6c629a5659cb47ff73de53

**Comment by PowerOfUniverse** [comment]
As for the number of people killed ... By default, it appears when you open a large map.

**Comment by IAmAHumanIThink** [comment]
How. Do. You. Update. So. Fast.

**Comment by 00petar00** [comment]
Its understandable that it will take some time, thanks for all the hard work.

**Comment by ALEXXANDRO23** [comment]
Mmmmm okey...........By the way Thank you for removing the notification * OK Cheat has been turned On! * :D

**Comment by PowerOfUniverse** [comment]
https://github.com/PowerOfUniverse/Surviv.io-Cheats/projects/1
