### ISSUE TITLE
Not functioning on the new update

### ISSUE THREAD

**Issue by reflexin** [PowerOfUniverse/Surviv.io-Cheats#9]
Self-explanatory.

**Comment by PowerOfUniverse** [comment]
I can ask for the extension version and photos of bugs from the console :)?

**Comment by PanKot** [comment]
have you downloaded latest version?
![image](https://user-images.githubusercontent.com/43040661/45318175-64497100-b53c-11e8-9236-2c989657fb11.png)

**Comment by BillyTheAntiBully** [comment]
Even with the Update , it doesn't work ;'(

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/45342040-01d48d00-b59d-11e8-8ca9-8fff2e5b7907.png)

**Comment by PowerOfUniverse** [comment]
![image](https://user-images.githubusercontent.com/42821489/45342056-0ac55e80-b59d-11e8-80cf-890cc7bbfd52.png)

**Comment by killercloudj** [comment]
There an other update?

**Comment by PowerOfUniverse** [comment]
This problem is closed ... If there are new ones, please create a new topic ...
